import { generateAuthHeaders, validateUser } from '@/lib/authorizer';
import { redirect } from 'next/navigation';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const DashboardLayout = async ({ children }: { children: React.ReactNode }) => {
  const isUserValidated = await validateUser();
  if (!isUserValidated) redirect('/authenticate');

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default DashboardLayout;
